using LojaSistema.Api.Models;

namespace LojaSistema.Api.Responses;

public sealed record PedidoClienteResponse(
    Guid Id,
    string NomeCliente,
    string EmailCliente,
    string? TelefoneCliente,
    string? DocumentoCliente,
    FormaPagamento FormaPagamento,
    StatusPedidoOnline Status,
    string EnderecoEntrega,
    string? CepEntrega,
    string? RuaEntrega,
    string? NumeroEntrega,
    string? ComplementoEntrega,
    string? BairroEntrega,
    string? CidadeEntrega,
    string? EstadoEntrega,
    string? Observacao,
    string? CupomCodigo,
    decimal TotalBruto,
    decimal Desconto,
    Guid? OpcaoEntregaId,
    string? EntregaNome,
    decimal EntregaValor,
    int? EntregaPrazoMinimoDias,
    int? EntregaPrazoMaximoDias,
    string? CodigoRastreio,
    string? ObservacaoEntrega,
    DateTime? RastreamentoAtualizadoEm,
    string? ReferenciaPagamento,
    string? ObservacaoPagamento,
    string? GatewayPagamentoProvedor,
    string? GatewayPagamentoId,
    string? GatewayPagamentoStatus,
    string? PixCopiaECola,
    string? PixQrCodeBase64,
    DateTime? PixExpiraEm,
    string? UrlPagamento,
    DateTime? PagamentoAtualizadoEm,
    DateTime? PagamentoConfirmadoEm,
    decimal Total,
    DateTime CriadoEm,
    IReadOnlyList<ItemPedidoClienteResponse> Itens);

public sealed record ItemPedidoClienteResponse(
    Guid ProdutoId,
    string ProdutoNome,
    string? Tamanho,
    string? Cor,
    string? Modelo,
    int Quantidade,
    decimal PrecoUnitario,
    decimal Subtotal);
